var bananaPrice = 12;
console.log(bananaPrice);
var relationship = 0-10;
console.log( typeof relationship);
var name = "kolimoddi";
console.log(name);
var isHot = true;
console.log(typeof isHot);
var promise = 'Since I am hard working, I will be a successfull person';
console.log(promise.split('I'));
var number1 = '25';
var number2 = '25.5';
number1 = parseInt(number1);
number2 = parseFloat(number2);
console.log(number1 + number2);
var price1 = 35;
var price2 = 25;
var total = price1 + price2;
console.log(total);
var price3 = 2;
var price4 = 11;
var reminder = price4 % price3;
console.log(reminder);
price3++;
price4--;
var number = Math.random()*100;
console.log(number);